version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gpmonde_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - gpmonde_network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./BackGp
    container_name: gpmonde_backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./BackGp/uploads:/app/uploads
    networks:
      - gpmonde_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./GpFront
    container_name: gpmonde_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - gpmonde_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s  # Délai avant de commencer le healthcheck

networks:
  gpmonde_network:
    driver: bridge

volumes:
  mysql_data:

