version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: gpmonde_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Memko@root
      MYSQL_DATABASE: gpmonde_db
      MYSQL_USER: gpuser
      MYSQL_PASSWORD: GpMonde@2022
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - gpmonde_network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./BackGp
    container_name: gpmonde_backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gpmonde_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: gpuser
      SPRING_DATASOURCE_PASSWORD: GpMonde@2022
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./BackGp/uploads:/app/uploads
    networks:
      - gpmonde_network
    restart: unless-stopped

  frontend:
    build: ./GpFront
    container_name: gpmonde_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - gpmonde_network
    restart: unless-stopped

networks:
  gpmonde_network:
    driver: bridge

volumes:
  mysql_data: