version: '3.8'

services:
  # Application Frontend Angular
  frontend:
    build:
      context: ./GpFront
      dockerfile: Dockerfile
    container_name: gp-front
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always
    networks:
      - gp-network
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro

  # Application Backend Spring Boot
  backend:
    build:
      context: ./BackGp
      dockerfile: Dockerfile
    container_name: gp-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gpmonde_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=ojJMx7uTkjO3Ov5BOjUimTFkk5Nb+zXvW+6wSRQUqSZeR9OjhseXki3vSA055PApH5ApNPXngdkkFfwOtax4eg==
    restart: always
    networks:
      - gp-network

  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: gp-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gpmonde_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - gp-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Optionnel : PHPMyAdmin pour administrer la base de données
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gp-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: always
    networks:
      - gp-network

volumes:
  mysql-data:

networks:
  gp-network:
    driver: bridge