version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Memko@root
      MYSQL_DATABASE: gpmonde_db
      MYSQL_USER: gpuser
      MYSQL_PASSWORD: GpMonde@2022
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - gpmonde_network
    restart: unless-stopped

  backend:
    build: ./BackGp
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gpmonde_db
      SPRING_DATASOURCE_USERNAME: gpuser
      SPRING_DATASOURCE_PASSWORD: GpMonde@2022
    networks:
      - gpmonde_network
    restart: unless-stopped

  frontend:
    build: ./GpFront
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - gpmonde_network
    restart: unless-stopped

networks:
  gpmonde_network:

volumes:
  mysql_data:
