version: '3'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gp-front
    ports:
      - "80:80"
      - "443:443"  # Ajout du port HTTPS
    volumes:
      - ./ssl:/etc/nginx/ssl  # Volume pour les certificats SSL
    restart: always
