version: '3.8'

services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: gp-mysql
    environment:
      - MYSQL_DATABASE=gpmonde_db
      - MYSQL_USER=user_gpmonde
      - MYSQL_PASSWORD=GpMonde@2022
      - MYSQL_ROOT_PASSWORD=Memko@2022
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - gp-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application Backend Spring Boot
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gp-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gpmonde_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=user_gpmonde
      - SPRING_DATASOURCE_PASSWORD=GpMonde@2022
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=ojJMx7uTkjO3Ov5BOjUimTFkk5Nb+zXvW+6wSRQUqSZeR9OjhseXki3vSA055PApH5ApNPXngdkkFfwOtax4eg==
      - JWT_EXPIRATION=86400000
      - JAVA_OPTS=-Xms256m -Xmx512m
    volumes:
      - app-logs:/app/logs
    restart: always
    networks:
      - gp-network

  # PHPMyAdmin pour administrer la base de données
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gp-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - UPLOAD_LIMIT=300M
      - MAX_EXECUTION_TIME=600
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - gp-network

volumes:
  mysql-data:
  app-logs:

networks:
  gp-network:
    driver: bridge